[package]
name = "ccbenchmark"
version = "0.1.0"
edition = "2024"

[lib]
name = "ccbenchmark"
crate-type = ["cdylib"]

[dependencies]
pyo3 = { version = "0.26.0", features = ["extension-module"] }
strum = "0.27.2"
strum_macros = "0.27.2"