[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "ccbenchmark"
version = "0.0.1"
dependencies = []

[project.scripts]
ccbenchmark = "ccbenchmark.__main__:entrypoint"