# ccbenchmark/_ccbenchmark.pyi
class Profile:
    def __new__(cls) -> "Profile": ...
    def __init__(self) -> None: ...
    selected_indicies: list[int]
    unit: str

class Manager:
    def __new__(cls) -> "Manager": ...
    def __init__(self) -> None: ...
    def emplace(self, metric_count: int, iteration_count: int, unit_str: str) -> None: ...
    def run_profile(self, profile: Profile) -> list[list[str]]: ...
    def set(self, benchmark_index: int, metric_index: int, iteration_index: int, value: float, unit_str: str) -> None: ...